namespace Krypton.Core.Architecture
{
    public enum VMOpCode
    {
        Nop,

        Ldstr,

        Call,
        Callvirt,

        Br,
        BrTrue,
        BrLessThan,
        BrGreaterThan,
        BrLessOrEqual,
        BrGreaterOrEqual,
        BrEqual,
        BrNotEqual,
        BrFalse,

        Ldloc,
        Ldloca,
        Stloc,
        Ldfld,
        Ldsfld,
        Stsfld,
        Stfld,

        Pop,
        Dup,

        Ldc_I4,
        Ldc_R4,
        Ldc_R8,
        Ldelem_Ref,
        Ldelem_U1,
        Stelem_Ref,
        Stelem_I1,
        Add,
        Ceq,
        Xor,
        Shl,
        Shr,
        Neg,
        Ldnull,
        Ldtoken,
        Switch,

        Ldarg,
        Ldlen,
        Ldelema,
        Ldobj,
        Stobj,
        Conv_I4,
        Conv_I8,
        Conv_U1,
        Not,
        Sub,
        Newarr,
        Newobj,
        Unbox_Any,
        Ret,
        Leave,
        EndFinally,

        // Keep new values appended so existing numeric opcode identifiers remain stable.
        Box,
        Constrained,

        // A cast that yields null on failure is behaviourally distinct from one that
        // throws, and taking the address of a field is distinct from loading it.
        // Leaving these out silently forced such bytes onto a wrong opcode.
        Isinst,
        Castclass,
        Ldsflda,
        Ldflda,
        Mul,
        Throw,
        Conv_U8,
        Conv_U4,
        Conv_Ovf_I4,

        // Remaining structurally representable CLR families. New members are
        // append-only so the frozen mappings above keep their numeric identity.
        Add_Ovf,
        Add_Ovf_Un,
        Sub_Ovf,
        Sub_Ovf_Un,
        Mul_Ovf,
        Mul_Ovf_Un,
        Div,
        Div_Un,
        Rem,
        Rem_Un,
        And,
        Or,
        Shr_Un,

        Conv_I1,
        Conv_I2,
        Conv_U2,
        Conv_I,
        Conv_U,
        Conv_R4,
        Conv_R8,
        Conv_R_Un,
        Conv_Ovf_I1,
        Conv_Ovf_I1_Un,
        Conv_Ovf_I2,
        Conv_Ovf_I2_Un,
        Conv_Ovf_I4_Un,
        Conv_Ovf_I8,
        Conv_Ovf_I8_Un,
        Conv_Ovf_U1,
        Conv_Ovf_U1_Un,
        Conv_Ovf_U2,
        Conv_Ovf_U2_Un,
        Conv_Ovf_U4,
        Conv_Ovf_U4_Un,
        Conv_Ovf_U8,
        Conv_Ovf_U8_Un,
        Conv_Ovf_I,
        Conv_Ovf_I_Un,
        Conv_Ovf_U,
        Conv_Ovf_U_Un,

        BrLessThan_Un,
        BrGreaterThan_Un,
        BrLessOrEqual_Un,
        BrGreaterOrEqual_Un,
        Rethrow,

        Unbox,
        Ldarga,
        Starg,

        Ldelem_I,
        Ldelem_I1,
        Ldelem_I2,
        Ldelem_I4,
        Ldelem_I8,
        Ldelem_U2,
        Ldelem_U4,
        Ldelem_R4,
        Ldelem_R8,
        Ldelem,
        Stelem_I,
        Stelem_I2,
        Stelem_I4,
        Stelem_I8,
        Stelem_R4,
        Stelem_R8,
        Stelem,

        Initobj,
        Cpobj,
        Sizeof,
        Localloc,
        Mkrefany,
        Refanyval,
        Refanytype,

        // The VM record format has a dedicated Int64 operand form.
        Ldc_I8,

        // A comparison pushed as a value (e.g. `bool b = x > y;`) is behaviourally
        // distinct from the same comparison used as a branch condition — leaving
        // these out silently forced such handler bytes onto a wrong opcode.
        Cgt,
        Cgt_Un,
        Clt,
        Clt_Un
    }
}
